# Generated by Django 4.2.6 on 2023-10-23 15:16

from django.db import migrations, models
import farmacia_ventas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=100, validators=[farmacia_ventas.validators.validation_nombre_cliente]),
        ),
        migrations.AlterField(
            model_name='farmaceutico',
            name='nombre',
            field=models.CharField(max_length=100, validators=[farmacia_ventas.validators.validation_nombre_farmaceutico]),
        ),
    ]
